// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ConversationSubscriptionController from "./conversation_subscription_controller"
application.register("conversation-subscription", ConversationSubscriptionController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import NavbarController from "./navbar_controller"
application.register("navbar", NavbarController)

import OnboardingController from "./onboarding_controller"
application.register("onboarding", OnboardingController)

import SearchMentorsController from "./search_mentors_controller"
application.register("search-mentors", SearchMentorsController)

import SwiperController from "./swiper_controller"
application.register("swiper", SwiperController)
